### ISSUE TITLE
Bug in filter page with run

### ISSUE THREAD

**Issue by ghost** [tests-assistant/tests-assistant#23]
Internal Server Error: /test/filter
Traceback (most recent call last):
  File "/home/aboubekki/.virtualenvs/ta/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/home/aboubekki/src/perso/tests-assistant/src/assistant/views.py", line 99, in test_filter
    request.session.pop('current')
  File "/home/aboubekki/.virtualenvs/ta/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 61, in pop
    return self._session.

**Comment by kra3** [comment]
https://github.com/amirouche/tests-assistant/blob/master/src/assistant/views.py#L99

That's caused by my change. I'll take care of it.

Do you know, how to reproduce it?
